// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPE4i-GkJDvpe63QRcaTLbdmTt00U7IZE',
    appId: '1:653145061959:web:e5aeb7fdb868091b9d4f62',
    messagingSenderId: '653145061959',
    projectId: 'ppb-proyek-akhir',
    authDomain: 'ppb-proyek-akhir.firebaseapp.com',
    storageBucket: 'ppb-proyek-akhir.appspot.com',
    measurementId: 'G-92XVJZX720',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gVvQdtjzpbComy3Pt9JhsXJJ_jLJ4k0',
    appId: '1:653145061959:android:46d84453d765df529d4f62',
    messagingSenderId: '653145061959',
    projectId: 'ppb-proyek-akhir',
    storageBucket: 'ppb-proyek-akhir.appspot.com',
  );
}
